language: node_js
node_js:
  - "14.16.0"

cache:
  directories:
    - node_modules
  yarn: false

os:
  - osx
  - linux

addons:
   apt:
     packages:
       - libsecret-1-dev
 
before_install:
  - rm -fr package-lock.json
  - |
    if [ $TRAVIS_OS_NAME == "linux" ]; then
      export DISPLAY=':99.0'
      /usr/bin/Xvfb :99 -screen 0 1024x768x24 > /dev/null 2>&1 &
    fi

install:
  - npm i -g vsce
  - npm install
  - npm run vscode:prepublish

script:
  - if [ $TRAVIS_OS_NAME == "linux" ]; then
      npm dedupe;
    fi
  - npm run lint
  - npm test --silent
  - vsce package -o LiveServer-$TRAVIS_TAG-$TRAVIS_OS_NAME.vsix

deploy:
  provider: releases
  api_key: $github_token
  file: "*.vsix"
  file_glob: true
  skip_cleanup: true
  on:
    tags: true
