environment:
  ELECTRON_NO_ATTACH_CONSOLE: 1

branches:
    only:
      - master

install:
  - ps: Update-NodeJsInstallation (Get-NodeJsLatestBuild 14.16.0)

build_script:
  - rm -fr package-lock.json
  - npm install
  - npm run vscode:prepublish

test_script:
  - npm run lint
  - npm test
